### ISSUE TITLE
Idea for quicker closing

### ISSUE THREAD

**Issue by ChromeAdmin** [ChromeAdmin/zoom-meetings-page-auto-closer#1]
Look into triggering the close sooner because tab loses focus?

That is typically an indicator that the user moved on to the Zoom

**Comment by ChromeAdmin** [comment]
Although, this is only an educated guess with the risk of annoyingly closing the zoom tab too early.

Maybe instead, offer a big button "Close Now" so the user can close more quickly without hunting and hovering the mouse around for the tab's x

**Comment by peterzejda** [comment]
Another alternative might be to trigger a shorter timer based on when the tab loses focus (perhaps a few seconds)? 

A similar option would be to make the amount of time to wait be configurable (ie. a user settable option for the extension), but that seems like more effort.

**Comment by ChromeAdmin** [comment]
@peterzejda , the amount of wait time is user configurable now. :)

**Comment by neooleg** [comment]
> @peterzejda , the amount of wait time is user configurable now. :)

@ChromeAdmin could you please point us to a doc / link to find how to configure that? 

Thanks!

**Comment by ChromeAdmin** [comment]
@neooleg , I updated the readme and I updated the screenshot. Apologies, both were old.

https://github.com/ChromeAdmin/meetings-page-auto-closer-for-zoom#:~:text=Easily%20change%20the%20countdown%20time

and scroll down and see the screenshot.

**Comment by neooleg** [comment]
@ChromeAdmin thanks a lot the how-to updated. Although, now I see that the problem for me was that the offered alternate times didn't appear on particular machine. Now it's OK.

BTW, could you please advise why don't you let users set a custom time? (e.g. 1 second)
