### ISSUE TITLE
Please update the extension play store version

### ISSUE THREAD

**Issue by pplupo** [ChromeAdmin/zoom-meetings-page-auto-closer#7]
I can see you have the 5 seconds option (I rather have it user-defined, I'd set it to even lower, 0s maybe) but the play store version (latest release as of today) doesn't have any option. Can you please update it?

**Comment by aekdb** [comment]
> Echoing pplupo, I would also love to see a user-defined delay

Third this sentiment.

**Comment by jboyle-ld** [comment]
Ok, it took me a really long time to figure it out, but after looking through previous issue submissions, I realized that you had already implemented a solution for the user to set a timeout interval, I just couldn't find any way to access it (afaict, its not documented anywhere). 

For anyone else who stumbles on this, when you see the auto-closer popup for the first time, there's a little yellow banner below the countdown, and you'll see the message, "20s not your speed?" with a small blue link to 20s and 15s, clicking on the lowest number in the set presents additional value pairs until you reach 5s which is the lowest threshold.

That's all I needed, I'm happy now, just wish it was easier to find (eg. right-clicking on the extension icon in the menubar)

**Comment by ChromeAdmin** [comment]
Thanks! I agree that it could be more intuitive.
